// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrações usam a conexão direta (não-pooled) da Neon — o pool via PgBouncer não
    // sustenta de forma confiável o advisory lock que o `prisma migrate deploy` precisa,
    // causando falhas intermitentes (P1002) no build. A aplicação em si (lib/db.ts) continua
    // usando DATABASE_URL (pooled) via @prisma/adapter-pg, sem nenhuma mudança de comportamento.
    url: process.env["DATABASE_URL_UNPOOLED"] || process.env["DATABASE_URL"],
  },
});
